#!/usr/bin/env python
"""Create assignment and configuration for the tiled catalog (for PSQL).

NOTE: Does NOT create the catalog databases and roles in PSQL.

Master registry file `assignments.yml` must exist.

- Creates credentials to use with PSQL
- Generates a database connection URI
- updates the `assignments.yml` file with the new catalog
- writes an init SQL (to configure PSQL for this catalog)
- writes a tiled config file
"""

# TODO:  Only if expanded to interact with PSQL server:
#          * check if postgres role already exists
#          * check if postgres databases already exist

import argparse
import datetime
import getpass
import os
import pathlib
import socket
import textwrap
import uuid

from dotenv import set_key

try:
    from ruamel.yaml import YAML
    from ruamel.yaml.comments import CommentedMap
except Exception as _exc:  # pragma: no cover - optional dependency
    YAML = None
    CommentedMap = dict
    _ruamel_import_error = _exc

PSQL_HOST = "wow.xray.aps.anl.gov"
PSQL_PORT = 5432
SERVER = f"{PSQL_HOST}:{PSQL_PORT}"
BS_ADMIN = "bsadmin"
ASSIGNMENTS_FILE = "assignments.yml"
THISDIR = pathlib.Path(__file__).parent
HOSTNAME = socket.gethostname() or "localhost"
USERNAME = getpass.getuser() or __name__
SQL_INIT_FILE = "init.sql"
TILED_CONFIG_FILE = "config.yml"

yaml = YAML()
yaml.preserve_quotes = True

# Load the assignments file.
if YAML is None:
    raise RuntimeError(
        "ruamel.yaml is required for comment-preserving YAML edits."
        #
        " Install with: pip install ruamel.yaml"
    )


def build_uri(cat: str, passwd: str) -> str:
    """Return a PostgreSQL connection URI for the catalog using the given password.

    The URI is suitable for passing to client libraries and psql.
    """
    user = create_user(cat)
    return f"postgresql://{user}:{passwd}@{SERVER}/{cat}-bluesky"


def catalog_registered(catalog: str) -> bool:
    """Return True if catalog is registered in assignments file."""
    assignments = read_assignments(ASSIGNMENTS_FILE)
    return assignments["catalogs"] is not None and catalog in assignments["catalogs"]


def create_init_sql(cat: str, passwd: str, uri: str) -> str:
    """Return the init SQL text to create the role, databases, and grants for the catalog.

    The returned SQL creates a role with the supplied password, two databases
    (catalog and storage), and grants the common privileges. The provided URI
    is included as a comment for operator convenience.
    """
    user = create_user(cat)
    catalog_db = f"{cat}-bluesky"
    storage_db = f"{catalog_db}-storage"
    sql_code = f"""\
        -- Init SQL generated by create_new_credentials
        -- Review before executing in production

        -- URI: {uri}

        CREATE ROLE "{user}"
            WITH LOGIN PASSWORD '{passwd}';

        CREATE DATABASE "{catalog_db}"
            ENCODING 'utf8'
            OWNER "{user}";

        CREATE DATABASE "{storage_db}"
            OWNER "{user}";

        GRANT CONNECT ON DATABASE "{catalog_db}"
            TO "{user}";
        GRANT CREATE ON DATABASE "{catalog_db}"
            TO "{user}";

        GRANT CONNECT ON DATABASE "{storage_db}"
            TO "{user}";
        GRANT CREATE ON DATABASE "{storage_db}"
            TO "{user}";

        GRANT USAGE ON SCHEMA public TO "{user}";
        GRANT CREATE ON SCHEMA public TO "{user}";
        GRANT SELECT, INSERT, UPDATE, DELETE
            ON ALL TABLES
            IN SCHEMA public
            TO "{user}";
        """
    return textwrap.dedent(sql_code)


def create_passkey() -> str:
    """Generate and return a short random password (format: hhhh-HHHH-hhhh)."""
    u = uuid.uuid4().hex[:12]
    return f"{u[:4]}-{u[4:8].upper()}-{u[8:]}"


def create_user(cat: str) -> str:
    """Return the database role name for a given catalog (e.g. 'bs-<cat>')."""
    return f"bs-{cat}"


def read_assignments(assignments) -> dict:
    """Read the assignments file."""
    with open(assignments, "r", encoding="utf-8") as fh:
        data = yaml.load(fh)
    return data


def update_assignments(catalog, uri, storage_uri, contact):
    """
    Update the assignments.yml file with a new catalog entry.
    """
    data = read_assignments(ASSIGNMENTS_FILE)

    # Build the new entry
    dt = datetime.datetime.now()
    comment = f"{dt.strftime('%Y-%m-%d')} Created by {USERNAME} on {HOSTNAME}"

    template = f"""
    {catalog}:
        contact: {contact!r}
        comments:
        - {comment!r}
        uri: {uri!r}
        storage_uri: {storage_uri!r}
    """
    entry = yaml.load(template)

    # add the new catalog
    if data["catalogs"] is None:
        data["catalogs"] = {}
    data["catalogs"].update(**entry)

    # Write with new catalog
    with open(ASSIGNMENTS_FILE, "w", encoding="utf-8") as fh:
        yaml.dump(data, fh)


def write_init_sql(path: str, cat: str, passwd: str, uri: str) -> None:
    """Write the init SQL to path (mode 0600) and print a concise runnable snippet.

    The function writes the init SQL file with restrictive permissions and then
    prints example commands to run the SQL as the administrator and to verify
    the resulting databases as the created catalog user.
    """
    bsadmin = BS_ADMIN
    sql = create_init_sql(cat, passwd, uri)
    sql += "\n"
    sql += f"-- psql -h {PSQL_HOST} -p {PSQL_PORT} -U {bsadmin} -d postgres -f {path}\n"
    # write file with restrictive permissions (600)
    old_umask = os.umask(0o177)
    try:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(sql)
    finally:
        os.umask(old_umask)
    try:
        os.chmod(path, 0o600)
    except Exception:
        pass

    create_user(cat)


def write_tiled_config(catalog, config_file) -> None:
    """Write a new config_file for tiled serving the catalog."""
    assignments = read_assignments(ASSIGNMENTS_FILE)
    cat_assignment = assignments["catalogs"][catalog]
    uri = cat_assignment["uri"]
    storage_uri = cat_assignment["storage_uri"]
    dt = datetime.datetime.now()

    template = f"""
    # tiled server configuration file
    # Created: {dt.strftime('%Y-%m-%d')} by {USERNAME} on {HOSTNAME}

    # tiled serve config {config_file} --api-key SECRET

    authentication:
      allow_anonymous_access: true

    uvicorn:
        host: 0.0.0.0
        port: 8000

    trees:

    - path: {catalog}
      tree: catalog
      args:
        specs:
        - name: CatalogOfBlueskyRuns
        uri: {uri}

        writable_storage:
        - {storage_uri}

        readable_storage: []

        init_if_not_exists: false
    """
    entry = yaml.load(template)

    with open(config_file, "w", encoding="utf-8") as fh:
        yaml.dump(entry, fh)


# ----- command-line interface --------------------


def parse_args(argv=None):
    """Parse and return command-line arguments (catalog , contact)."""
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("cat", help="catalog name")
    p.add_argument(
        "contact",
        type=str,
        help="beamline contact person",
        default="BEAMLINE CONTACT HERE",
    )
    return p.parse_args(argv)


def main(argv=None):
    """CLI entry point: generate password, print URI, and optionally write init SQL."""
    args = parse_args(argv)
    if catalog_registered(args.cat):
        raise KeyError(f"Catalog '{args.cat}' is already registered.")
    dt = datetime.datetime.now()
    passwd = f"{create_passkey()}-bs-{dt.year}-{dt.month:02d}"
    uri = build_uri(args.cat, passwd)
    storage_uri = f"{uri}-storage"
    # print(uri)

    # create subdirectory and write URI in .env
    subdir = THISDIR / f"{args.cat}-tiled-server"
    subdir.mkdir()
    env_path = subdir / '.env'
    env_path.touch(exist_ok=True)
    set_key(str(env_path), "PSQL_CATALOG_URI", uri, export=True, quote_mode="never")

    update_assignments(args.cat, uri, storage_uri, args.contact)

    path= subdir / SQL_INIT_FILE
    write_init_sql(str(path), args.cat, passwd, uri)

    path= subdir / TILED_CONFIG_FILE
    write_tiled_config(args.cat, str(path))


if __name__ == "__main__":
    main()
