authentication:
  # The default is false. Set to true to enable any HTTP client that can
  # connect to _read_. An API key is still required to write.
  allow_anonymous_access: true
  # single_user_api_key: secret
trees:
  - path: /
    tree: catalog
    args:
      uri: sqlite:////Users/ecodrea/eric-bits/catalog.db
      writable_storage: 
      - "/data"
      - duckdb:////Users/ecodrea/eric-bits/storage.duckdb
      readable_storage: 
      - "/data"
      # This creates the database if it does not exist. This is convenient, but in
      # a horizontally-scaled deployment, this can be a race condition and multiple
      # containers may simultaneously attempt to create the database.
      # If that is a problem, set this to false, and run:
      #
      # tiled catalog init URI
      #
      # separately.
      init_if_not_exists: true

# tiled server configuration file

# authentication:
#       # The default is false.
#       # When true, any HTTP client that can connect has *read only* permission.
#       # An API key is still required to write.
#   allow_anonymous_access: true

# uvicorn:
#     host: 0.0.0.0
#     port: 8000


# trees:

# - path: developer
#   tree: catalog
#   args:
#     specs:
#     - name: CatalogOfBlueskyRuns
#     uri: 
#       postgresql://bs-developer:80ff-1845-d869-bs-2025-10@wow.xray.aps.anl.gov:5432/developer-bluesky
#     writable_storage:
#     - postgresql://bs-developer:80ff-1845-d869-bs-2025-10@wow.xray.aps.anl.gov:5432/developer-bluesky-storage
#     readable_storage: []
#     init_if_not_exists: false
 